### ISSUE TITLE
./setup.sh develop - requires setuptools>=17.1. on Fedora 21

### ISSUE THREAD

**Issue by psiinon** [mozilla/minion#37]
./setup.sh develop
running on Fedora 21 fails with:

Installed /home/simon/git/minion/minion-backend
Processing dependencies for minion-backend==0.1
Searching for mock
Reading https://pypi.python.org/simple/mock/
Best match: mock 1.3.0
Downloading https://pypi.python.org/packages/source/m/mock/mock-1.3.0.tar.gz#md5=73ee8a4afb3ff4da1b4afa287f39fdeb
Processing mock-1.3.0.tar.gz
Writing /tmp/easy_install-wDGgDp/mock-1.3.0/setup.cfg
Running mock-1.3.0/setup.py -q bdist_egg --dist-dir /tmp/easy_install-wDGgDp/mock-1.3.0/egg-dist-tmp-JMkkin
mock requires setuptools>=17.1. Aborting installation
error: Setup script exited with 1

**Comment by marumari** [comment]
Yeah, Fedora/Ubuntu/Redhat seem to install old versions of setuptools.  You can upgrade them with:

easy_install --upgrade setuptools
