### ISSUE TITLE
./setup.sh develop fails

### ISSUE THREAD

**Issue by thealmostrealmccoy** [mozilla/minion#38]
I cloned this repository in ubuntu and ran /setup.sh develop.

It fails when trying to install mock 1.3.0. "mock requires setuptools>=17.1"

I upgraded setuptool to version greater than 17.1 from here

https://pypi.python.org/pypi/setuptools/17.1.1#advanced-installation

Also installed mock using pip

https://github.com/NeuroML/pyNeuroML/issues/9

It did not make any difference.

I have reproduced the error below. Any pointers or thoughts to what could be the problem? Thanks

...
...
writing requirements to minion_backend.egg-info/requires.txt
writing minion_backend.egg-info/PKG-INFO
writing namespace_packages to minion_backend.egg-info/namespace_packages.txt
writing top-level names to minion_backend.egg-info/top_level.txt
writing dependency_links to minion_backend.egg-info/dependency_links.txt
reading manifest file 'minion_backend.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no files found matching '*.txt' under directory 'minion'
warning: no files found matching '*.yaml' under directory 'minion'
warning: no files found matching '*.yml' under directory 'minion'
warning: no files found matching '*.json' under directory 'minion'
warning: no files found matching '*.j2' under directory 'minion'
writing manifest file 'minion_backend.egg-info/SOURCES.txt'
running build_ext
Creating /home/vpalathuruthil/Development/minion/env/lib/python2.7/site-packages/minion-backend.egg-link (link to .)
minion-backend 0.1 is already the active version in easy-install.pth
Installing minion-backend-api script to /home/vpalathuruthil/Development/minion/env/bin
Installing minion-create-plan script to /home/vpalathuruthil/Development/minion/env/bin
Installing minion-db-init script to /home/vpalathuruthil/Development/minion/env/bin
Installing minion-create-user script to /home/vpalathuruthil/Development/minion/env/bin
Installing minion-delete-user script to /home/vpalathuruthil/Development/minion/env/bin
Installing minion-get-users script to /home/vpalathuruthil/Development/minion/env/bin
Installing minion-plugin-worker script to /home/vpalathuruthil/Development/minion/env/bin
Installing minion-scan script to /home/vpalathuruthil/Development/minion/env/bin
Installing minion-state-worker script to /home/vpalathuruthil/Development/minion/env/bin
Installing minion-scan-worker script to /home/vpalathuruthil/Development/minion/env/bin
Installing minion-plugin-runner script to /home/vpalathuruthil/Development/minion/env/bin
Installing minion-scanschedule-worker script to /home/vpalathuruthil/Development/minion/env/bin
Installing minion-scanscheduler script to /home/vpalathuruthil/Development/minion/env/bin

Installed /home/vpalathuruthil/Development/minion/minion-backend
Processing dependencies for minion-backend==0.1
Searching for mock
Reading https://pypi.python.org/simple/mock/
Best match: mock 1.3.0
Downloading https://pypi.python.org/packages/source/m/mock/mock-1.3.0.tar.gz#md5=73ee8a4afb3ff4da1b4afa287f39fdeb
Processing mock-1.3.0.tar.gz
Writing /tmp/easy_install-YnD8i5/mock-1.3.0/setup.cfg
Running mock-1.3.0/setup.py -q bdist_egg --dist-dir /tmp/easy_install-YnD8i5/mock-1.3.0/egg-dist-tmp-a3TJVz
mock requires setuptools>=17.1. Aborting installation
error: Setup script exited with 1

**Comment by marumari** [comment]
Did you upgrade setuptools after switching to your virtualenv?

Try switching to your virtualenv and run this:
```
$ python                                                                                                                                                             
Python 2.7.10 (default, Jul 13 2015, 12:05:58)
[GCC 4.2.1 Compatible Apple LLVM 6.1.0 (clang-602.0.53)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import setuptools
>>> setuptools.__version__
'18.2'
```

If it shows the old setuptools version, my guess is that you upgraded the system python, and not the one in your virtualenv.

**Comment by thealmostrealmccoy** [comment]
Thanks for your response. I followed your instruction and ran the commands. I got the same output as the one you have reproduced in your response. I presume it means I have the up to date version of setuptools?

```
xxx@ubuntu:~/Development/minion/env$ python
Python 2.7.6 (default, Jun 22 2015, 17:58:13) 
[GCC 4.8.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import setuptools
>>> setuptools.__version__
'18.2'
>>> 
```

**Comment by marumari** [comment]
Yep, that looks correct.  Does 'python setup.py develop' still fail, after switching to your virtualenv, with that version of setuptools?

**Comment by thealmostrealmccoy** [comment]
Yes....It still fails.....However I have found the root cause of the issue...

Basically I am a newbie to the world of python. So I did not grasp the concept of virtualenv in python.

I was following the instruction verbatim on the following page

https://github.com/mozilla/minion.

These instructions do not clearly indicate whether you need to run the script in a virtual environment.

So I switched to following the instruction on the following page

http://minion.readthedocs.org/en/latest/install_guide.html

These instruction show how to run the install in a virtualenv.

I still got the aforementioned error about obsolete setuptools. This time when I ran the version command on setuptools, it showed the version to be 2.2. So I upgraded to 18.2 using pip then ran  "setup.py develop" and voila it worked!

Thanks much for your help!

**Comment by marumari** [comment]
Great!  I plan on updating all the docs over the next couple days, so hopefully it'll be easier for people to get starting going forward from here.  :)
